repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 5.10.1
    hooks:
    - id: isort

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1.fla
    hooks:
    - id: flake8
